name: 02 - Workflow Events

#On peut mettre plusieurs évèments
#on:
#  - push
#  - pull_request
#On peut aussi définir les évèments comme des objets
#on:
#  push:
#  pull_request:
#Cela permet d'ajouter les options sur les evenements, par exemple le cron(comme batch)
#on:
#  push:
#  pull_request:
#  schedule:
#       - cron: "*/5 * * * *"
#  workflow_dispatch:
on:
  push:
  pull_request:
  schedule:
       - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: Show the trigger
            run: |
                echo "Event name: ${{ github.event_name }}"
            