name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        #0. Checkout the code in th repository
        #1. Install Deps of our React application
        #2. Executed automated tests

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Printing Folders
              run: ls