name: 05 - 1 - Event Filters and Activity Types

run-name: ${{ github.actor }} is learning GitHub Actions

#on:
#    pull_request:
#        types: [opened, synchronize]
#        branches: [main]

on: workflow_dispatch

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Message"
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"